site_name: NOMAD Workflows Documentation
site_description: |
  NOMAD custom and automatic workflow documentation.
site_author: FAIRmat consortium
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - How-to:
    - howtos/same_mainfile.md
  - References:
    - references/refs.md
  - Explanations: 
    - explanations/whyworkflows.md
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
